baseURL = "https://awesome.ipfs.io"
relativeURLs = true
title = "Awesome IPFS"
languageCode = "en-us"

[params]
  domain = "awesome.ipfs.io"
  name = "Awesome IPFS"
  title = "Awesome IPFS"
  description = "Useful resources for using IPFS and building things on top of it."
  author = "protocollabs"
